services:
  misskey-ai:
    build: .
    container_name: misskey-ai
    restart: unless-stopped
    
    volumes:
      # - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - ./logs:/app/logs
    
    environment:
      - MISSKEY_INSTANCE_URL=https://misskey.example.com
      - MISSKEY_ACCESS_TOKEN=your_access_token_here
      - DEEPSEEK_API_KEY=your_deepseek_api_key_here
      - DEEPSEEK_MODEL=deepseek-chat
      - DEEPSEEK_API_BASE=https://api.deepseek.com/v1
      - DEEPSEEK_MAX_TOKENS=1000
      - DEEPSEEK_TEMPERATURE=0.8
      - BOT_SYSTEM_PROMPT=你是一个可爱的AI助手，运行在Misskey平台上。请用简短、友好的方式发帖和回答问题。
      - BOT_AUTO_POST_ENABLED=true
      - BOT_AUTO_POST_INTERVAL=180
      - BOT_AUTO_POST_MAX_PER_DAY=8
      - BOT_AUTO_POST_VISIBILITY=public
      - BOT_AUTO_POST_PROMPT=生成一篇有趣、有见解的社交媒体帖子。
      - BOT_RESPONSE_MENTION_ENABLED=true
      - BOT_RESPONSE_CHAT_ENABLED=true
      - BOT_RESPONSE_CHAT_MEMORY=10
      - BOT_RESPONSE_POLLING_INTERVAL=60
      - API_TIMEOUT=30
      - API_MAX_RETRIES=3
      - DB_CLEANUP_DAYS=30
      - LOG_LEVEL=INFO
    
    # env_file:
    #   - .env
    
    healthcheck:
      test: ["CMD", "python", "-c", "from src.utils import health_check; exit(0 if health_check() else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s