services:
  misskey-bot:
    build: .
    container_name: misskey-bot
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    
    env_file:
      - .env
    
    healthcheck:
      test: ["CMD", "python", "-c", "from src.utils import health_check; exit(0 if health_check() else 1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s