"""项目核心常量定义"""

# API配置
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0
DEFAULT_API_TIMEOUT = 30

# DeepSeek API
DEEPSEEK_API_BASE_URL = "https://api.deepseek.com/v1"
DEFAULT_DEEPSEEK_MODEL = "deepseek-chat"
DEFAULT_MAX_TOKENS = 1000
DEFAULT_TEMPERATURE = 0.7

# Misskey API
DEFAULT_VISIBILITY = "public"

# HTTP状态码
HTTP_OK = 200
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_TOO_MANY_REQUESTS = 429
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504

# 机器人配置
DEFAULT_MAX_POST_LENGTH = 500
DEFAULT_AUTO_POST_INTERVAL_HOURS = 6
DEFAULT_MAX_DAILY_POSTS = 4
MAX_POST_LENGTH = 3000

# 性能配置
MAX_PROCESSED_ITEMS_CACHE = 500
DEFAULT_POLLING_INTERVAL = 60

# 可重试的HTTP状态码
RETRYABLE_HTTP_CODES = {
    HTTP_TOO_MANY_REQUESTS,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_BAD_GATEWAY,
    HTTP_SERVICE_UNAVAILABLE,
    HTTP_GATEWAY_TIMEOUT
}

# WebSocket配置
WS_HEARTBEAT_INTERVAL = 30
WS_RECONNECT_DELAY = 5
WS_MAX_RECONNECT_ATTEMPTS = 10

# 日志配置
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_PATH = "logs"

# 持久化配置
DEFAULT_DB_PATH = "data/bot_persistence.db"
DEFAULT_CLEANUP_DAYS = 7

# 配置文件
DEFAULT_CONFIG_PATH = "config.yaml"
DEFAULT_ENV_FILE = ".env"