DEEPSEEK_API_BASE_URL = "https://api.deepseek.com/v1"
DEFAULT_DEEPSEEK_MODEL = "deepseek-chat"
DEFAULT_MAX_TOKENS = 1000
DEFAULT_TEMPERATURE = 0.8

DEFAULT_AUTO_POST_ENABLED = True
DEFAULT_AUTO_POST_INTERVAL_MINUTES = 60
DEFAULT_MAX_DAILY_POSTS = 10
DEFAULT_AUTO_POST_VISIBILITY = "public"
DEFAULT_RESPONSE_MENTION_ENABLED = True
DEFAULT_RESPONSE_CHAT_ENABLED = True
DEFAULT_POLLING_INTERVAL = 60

DEFAULT_API_TIMEOUT = 30
DEFAULT_MAX_RETRIES = 3

DEFAULT_DB_PATH = "data/misskey_ai.db"
DEFAULT_CLEANUP_DAYS = 7

DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_PATH = "logs"

DEFAULT_CONFIG_PATH = "config.yaml"
DEFAULT_ENV_FILE = ".env"

MAX_PROCESSED_ITEMS_CACHE = 500

HTTP_OK = 200
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_TOO_MANY_REQUESTS = 429
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504

RETRYABLE_HTTP_CODES = {
    HTTP_TOO_MANY_REQUESTS,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_BAD_GATEWAY,
    HTTP_SERVICE_UNAVAILABLE,
    HTTP_GATEWAY_TIMEOUT
}

WS_HEARTBEAT_INTERVAL = 30
WS_RECONNECT_DELAY = 5
WS_MAX_RECONNECT_ATTEMPTS = 10